export const customers = [
  {
    id: "1",
    title: "ABC Traders",
    address: "123 Main St, Karachi Sindh",
    phone: "021-4567890",
    fax: "021-4567891",
    email: "info@abctraders.com",
    website: "www.abctraders.com",
    latitude: "24.866254",
    longitude: "67.022965",
  },
  {
    id: "2",
    title: "XYZ Corporation",
    address: "456 Business Ave, Lahore",
    phone: "042-1234567",
    fax: "042-1234568",
    email: "contact@xyz.com",
    website: "www.xyz.com",
    latitude: "31.5204",
    longitude: "74.3587",
  },
  {
    id: "3",
    title: "Iota Beverages",
    address: "789 Industrial Rd, Karachi",
    phone: "021-9876543",
    fax: "021-9876544",
    email: "info@iota.com",
    website: "www.iota.com",
    latitude: "24.9056",
    longitude: "67.1450",
  },
]

export const projects = [
  {
    id: "1",
    customer: "ABC Traders",
    title: "Retail Expansion",
    location: "Karachi",
    latitude: "31.3700",
    longitude: "74.2200",
    contactName: "John Smith",
    contactPhone: "0300-1234567",
    contactEmail: "john@abc.com",
  },
  {
    id: "2",
    customer: "XYZ Corporation",
    title: "Warehouse Setup",
    location: "Lahore",
    latitude: "31.5204",
    longitude: "74.3587",
    contactName: "Sarah Ahmed",
    contactPhone: "0321-9876543",
    contactEmail: "sarah@xyz.com",
  },
  {
    id: "3",
    customer: "Iota Beverages",
    title: "Beverage Bottling SCADA",
    location: "Karachi",
    latitude: "24.8566",
    longitude: "67.0228",
    contactName: "Zeeshan Rafiq",
    contactPhone: "0312-8899776",
    contactEmail: "zeeshan@iota.com",
  },
]

export const orders = [
  {
    id: "1",
    orderNumber: "ORD-001",
    erpNumber: "ERP-9001",
    customer: "ABC Traders",
    project: "Retail Expansion",
    amount: "50,000.00",
    created: "2025-10-30",
  },
  {
    id: "2",
    orderNumber: "ORD-002",
    erpNumber: "ERP-9002",
    customer: "XYZ Corporation",
    project: "Warehouse Setup",
    amount: "85,000.00",
    created: "2025-10-30",
  },
  {
    id: "3",
    orderNumber: "ORD-003",
    erpNumber: "ERP-9003",
    customer: "Engro",
    project: "ICI Port Qasim Plant",
    amount: "72,000.00",
    created: "2025-10-30",
  },
  {
    id: "4",
    orderNumber: "ORD-004",
    erpNumber: "ERP-9004",
    customer: "Centegy Technologies",
    project: "Textile Mill Energy Audit",
    amount: "15,000.00",
    created: "2025-10-30",
  },
  {
    id: "5",
    orderNumber: "ORD-005",
    erpNumber: "ERP-9005",
    customer: "Epsilon Steel",
    project: "Steel Plant Automation",
    amount: "98,000.00",
    created: "2025-10-30",
  },
]

export const assets = [
  {
    id: "1",
    customer: "ABC Traders",
    title: "Backup Diesel Generator",
    serialNumber: "SN-DG-004",
    project: "Retail Expansion",
    model: "DG-75KVA",
    category: "Power Supply",
    order: "ORD-001",
    manufacturer: "Caterpillar",
    barcode: "BAR-10004",
    description: "Provides emergency backup power for main facility.",
  },
  {
    id: "2",
    customer: "XYZ Corporation",
    title: "Server Rack",
    serialNumber: "SN-SR-001",
    project: "Warehouse Setup",
    model: "SR-42U",
    category: "IT Equipment",
    order: "ORD-002",
    manufacturer: "Dell",
    barcode: "BAR-10005",
    description: "Network server infrastructure.",
  },
]

export const tasks = [
  {
    id: "1",
    title: "Install Equipment",
    customer: "ABC Traders",
    project: "Retail Expansion",
    order: "ORD-001",
    asset: "Main Distribution Panel",
    duration: "4",
    completed: "Yes",
    created: "2025-10-30",
    startTime: "10/01/2025 09:00 AM",
    endTime: "10/01/2025 01:00 PM",
  },
  {
    id: "2",
    title: "System Configuration",
    customer: "ABC Traders",
    project: "Retail Expansion",
    order: "ORD-001",
    asset: "Main Distribution Panel",
    duration: "3",
    completed: "Yes",
    created: "2025-10-30",
    startTime: "10/02/2025 10:00 AM",
    endTime: "10/02/2025 01:00 PM",
  },
]

export const employees = [
  {
    id: "1",
    name: "John Doe",
    email: "john@bitsberg.com",
    phone: "0300-1234567",
    position: "Field Technician",
  },
  {
    id: "2",
    name: "Jane Smith",
    email: "jane@bitsberg.com",
    phone: "0321-9876543",
    position: "Project Manager",
  },
]
